spring.application.name=spring-ai

spring.ai.openai.api-key=${OPEN_AI_API_KEY}
spring.ai.openai.organization-id=${OPEN_AI_ORGANIZATION_ID}
spring.ai.openai.project-id=${OPEN_AI_PROJECT_ID}
spring.ai.openai.chat.options.model=gpt-4o